mlp:
    vars:
    - eta
    - lead_eta
    - lead_phi
    - lead_mvaID
    - regcol_pholead_PtOverM
    - sublead_eta
    - sublead_phi
    - sublead_mvaID
    - regcol_phosublead_PtOverM
    - regcol_lead_bjet_eta
    - regcol_lead_bjet_phi
    - regcol_lead_bjet_btag_WP_L
    - regcol_lead_bjet_btag_WP_M
    - regcol_lead_bjet_btag_WP_T
    - regcol_lead_bjet_btag_WP_XT
    - regcol_lead_bjet_btag_WP_XXT
    - regcol_sublead_bjet_eta
    - regcol_sublead_bjet_phi
    - regcol_sublead_bjet_btag_WP_L
    - regcol_sublead_bjet_btag_WP_M
    - regcol_sublead_bjet_btag_WP_T
    - regcol_sublead_bjet_btag_WP_XT
    - regcol_sublead_bjet_btag_WP_XXT
    - regcol_DeltaR_j1g1
    - regcol_DeltaR_j2g1
    - regcol_DeltaR_j1g2
    - regcol_DeltaR_j2g2
    - regcol_DeltaR_jg_min
    - regcol_CosThetaStar_CS
    - regcol_CosThetaStar_gg
    - regcol_CosThetaStar_jj
    - puppiMET_phi
    - puppiMET_pt
    - n_leptons
    - n_jets
    - regcol_chi_t0
    - regcol_chi_t1
    - regcol_DeltaPhi_j1MET
    - regcol_DeltaPhi_j2MET
    - regcol_VBF_first_jet_eta
    - regcol_VBF_first_jet_phi
    - regcol_VBF_second_jet_eta
    - regcol_VBF_second_jet_phi
    - regcol_VBF_first_jet_PtOverM
    - regcol_VBF_second_jet_PtOverM
    - regcol_VBF_jet_eta_prod
    - regcol_VBF_jet_eta_diff
    - regcol_VBF_jet_eta_sum
    - regcol_VBF_DeltaR_j1b1
    - regcol_VBF_DeltaR_j1b2
    - regcol_VBF_DeltaR_j2b1
    - regcol_VBF_DeltaR_j2b2
    - regcol_VBF_DeltaR_j1g1
    - regcol_VBF_DeltaR_j1g2
    - regcol_VBF_DeltaR_j2g1
    - regcol_VBF_DeltaR_j2g2
    - regcol_VBF_DeltaR_jb_min
    - regcol_VBF_DeltaR_jg_min
    - regcol_VBF_dijet_mass
    - regcol_HHbbggCandidate_eta
    - diphoton_PtOverM_ggjj
    - regcol_dijet_PtOverM_ggjj
    - deltaR_gg
    - regcol_lead_bjet_over_M_regressed
    - regcol_sublead_bjet_over_M_regressed
