sample_to_class: # processes and classes
    GGJets: is_non_resonant_bkg
    DDQCDGJET: is_non_resonant_bkg
    TTGG: is_non_resonant_bkg
    ttHtoGG_M_125: is_ttH_bkg
    BBHto2G_M_125: is_single_H_bkg
    GluGluHToGG_M_125: is_single_H_bkg
    VBFHToGG_M_125: is_single_H_bkg
    VHtoGG_M_125: is_single_H_bkg
    GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: is_GluGluToHH_sig

classes: # all classes
- is_non_resonant_bkg
- is_ttH_bkg
- is_single_H_bkg
- is_GluGluToHH_sig

weight_scheme_process: # how to weight each processes within a class
    # xsec : weight them according to the cross-section of each process
    # equal_weight: weight each process eqally, if there are two processes, you first weight the sum of each processes to be equal and then weight the whole class to be 1
    is_non_resonant_bkg: xsec 
    is_ttH_bkg: xsec
    is_single_H_bkg: xsec
    is_GluGluToHH_sig: xsec 

# some info for training
do_random_search: False
num_random_search: 1
weight_scheme: weighted_abs # weighted_only_positive # weighted_CRUW_abs # weighted_CRUW_only_positive
random_seed: 42
cuda_device: "0"
max_epoch: 300

# Decorrelation settings
use_DisCo: True
decorr_lambda: 10.0
disco_reduce_method: mean # mean, max, sum, quadrature
# disco_decorr_class_idx: [0,1,2,3] # index of the class to decorrel, e.g. 0 for signal-only
z_variables: # "Z dataset" variables to decorrelate against, e.g. mjj
- nonResReg_dijet_mass_DNNreg 
- mass
decorrelation_variables:
    var1:
        - mass
        # - nonResReg_dijet_mass_DNNreg
    var2:
        - nonResReg_dijet_mass_DNNreg
        # - is_non_resonant_bkg
        # - is_ttH_bkg
        # - is_single_H_bkg
        # - is_GluGluToHH_sig
upweight_params: # conservative SR upweighting parameters
    do_upweight: True
    max_upweight: 10.0
    min_upweight: 1.0 # values less than 1 will DECREASE the weight of events far from SR, so be careful
    sr_definition:
        score_midpoint: # score value at which upweight reaches 50% of max_upweight (ORDER SENSITIVE)
            th_nonRes: 0.45
            th_ttH: 0.65
            th_singleH: 0.45
            th_ggFHH: 0.85
        score_90_percent: # score value at which upweight reaches 90% of max_upweight (ORDER SENSITIVE)
            th_nonRes: 0.10
            th_ttH: 0.50
            th_singleH: 0.20
            th_ggFHH: 0.90



samples_info: 
    samples_path: /eos/cms/store/group/phys_b2g/HHbbgg/HiggsDNA_parquet/v3/ # samples path
    eras:
    - preEE
    - postEE
    - preBPix
    - postBPix
    preEE: # give relative path to
        GGJets: "Run3_2022/sim/preEE/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2022/sim/preEE/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2022/sim/preEE/TTGG/nominal/NOTAG_merged.parquet" 
        ttHtoGG_M_125: "Run3_2022/sim/preEE/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2022/sim/preEE/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2022/sim/preEE/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2022/sim/preEE/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2022/sim/preEE/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022/sim/preEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2022/sim/preEE/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2022/sim/preEE/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022/sim/preEE/TT.parquet"
    postEE:
        GGJets: "Run3_2022/sim/postEE/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2022/sim/postEE/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2022/sim/postEE/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2022/sim/postEE/ttHToGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2022/sim/postEE/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2022/sim/postEE/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2022/sim/postEE/VBFHToGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2022/sim/postEE/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022/sim/postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2022/sim/postEE/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2022/sim/postEE/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022/sim/postEE/TT.parquet"
    preBPix:
        GGJets: "Run3_2023/sim/preBPix/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2023/sim/preBPix/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2023/sim/preBPix/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2023/sim/preBPix/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2023/sim/preBPix/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2023/sim/preBPix/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2023/sim/preBPix/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2023/sim/preBPix/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2023/sim/preBPix/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2023/sim/preBPix/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022preEE/TT.parquet"
    postBPix:
        GGJets: "Run3_2023/sim/postBPix/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2023/sim/postBPix/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2023/sim/postBPix/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2023/sim/postBPix/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2023/sim/postBPix/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2023/sim/postBPix/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2023/sim/postBPix/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2023/sim/postBPix/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2023/sim/postBPix/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2023/sim/postBPix/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022preEE/TT.parquet"
    data:
        2022_EraE: "Run3_2022/data/Data_EraE_NOTAG_merged.parquet"
        2022_EraF: "Run3_2022/data/Data_EraF_NOTAG_merged.parquet"
        2022_EraG: "Run3_2022/data/Data_EraG_NOTAG_merged.parquet"
        2022_EraC: "Run3_2022/data/DataC_2022_NOTAG_merged.parquet"
        2022_EraD: "Run3_2022/data/DataD_2022_NOTAG_merged.parquet"
        2023_EraC: "Run3_2023/data/Data_EraD_NOTAG_merged.parquet"
        2023_EraD: "Run3_2023/data/Data_EraC_NOTAG_merged.parquet"

systematics:
- ScaleEB2G_IJazZ_down
- ScaleEB2G_IJazZ_up
- ScaleEE2G_IJazZ_up
- ScaleEE2G_IJazZ_down
- Smearing2G_IJazZ_down
- Smearing2G_IJazZ_up
- jec_syst_Total_down
- jec_syst_Total_up
- jer_syst_down
- jer_syst_up
- FNUF_down
- FNUF_up
- Material_down
- Material_up

# info to save in the parquets
save_all_columns_sim_nominal : True
save_all_columns_data : True
save_all_columns_sim_systematics : False

# Chunk size for converting akward arrays to pandas dataframes to alleviate memory pressure
write_chunk : 50000

# ========== Categorization ==========
class_name_map: # for mapping multiclass class names to other formats
    th_name_to_class_name: # bayesian_categorization.py format
        th_signal: th_ggFHH
        th_bg_0: th_nonRes
        th_bg_1: th_ttH
        th_bg_2: th_singleH
        th_bg_4: th_VBFHH

    th_name_to_ff_name: # score names that appear in FinalFit cat json file
        th_signal: "HH_score" # "ggHH_score" # "HH_score"
        th_bg_0: "nonRes_score"
        th_bg_1: "ttH_score"
        th_bg_2: "singleH_score"
        th_bg_4: "VBFHH_score"
class_criteria_inequality: # inequality for each class criteria: >, >=, <, <=
    th_signal: ">" # e.g. ggHH_score > 0.91005
    th_bg_0: "<" # e.g. nonRes_score < 0.061683
    th_bg_1: "<" # e.g. ttH_score < 0.045553
    th_bg_2: "<" # e.g. singleH_score < 0.054659
    th_bg_4: "<" # n.b. assuming this is correct -- it probably is
global_criteria_phrases: # add to all category criteria
- "dijet_mass > 80"
- "dijet_mass < 190"
# - "is_boosted == 0"
json_float_precision: -1 # -1 for no rounding


# ========== Merge samples for FinalFit ==========
merge_samples:
    samples: # Comment samples to exclude from merged parquet
    # - GGJets
    # - DDQCDGJET
    # - TTGG
    # - TT
    # - TTG_10_100
    # - TTG_100_200
    # - TTG_200
    - ttHtoGG_M_125
    - BBHto2G_M_125
    - GluGluHToGG_M_125
    - VBFHToGG_M_125
    - VHtoGG_M_125
    - GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00
    - GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00
    - GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00
    - GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00
    systs: # Comment systematics to exclude from merged parquet
    - ScaleEB2G_IJazZ_down
    - ScaleEB2G_IJazZ_up
    - ScaleEE2G_IJazZ_down
    - ScaleEE2G_IJazZ_up
    - Smearing2G_IJazZ_down
    - Smearing2G_IJazZ_up
    - jec_syst_Total_down
    - jec_syst_Total_up
    - jer_syst_down
    - jer_syst_up
    - FNUF_down
    - FNUF_up
    - Material_down
    - Material_up
    finalfit_syst_name_map: # pq: ff
        ScaleEB2G_IJazZ_down: ScaleEB2GIJazZDown01sigma
        ScaleEB2G_IJazZ_up: ScaleEB2GIJazZUp01sigma
        ScaleEE2G_IJazZ_down: ScaleEE2GIJazZDown01sigma
        ScaleEE2G_IJazZ_up: ScaleEE2GIJazZUp01sigma
        Smearing2G_IJazZ_down: Smearing2GIJazZDown01sigma
        Smearing2G_IJazZ_up: Smearing2GIJazZUp01sigma
        jec_syst_Total_down: jecsystDown01sigma
        jec_syst_Total_up: jecsystUp01sigma
        jer_syst_down: jersystDown01sigma
        jer_syst_up: jersystUp01sigma
        FNUF_down: FNUFDown01sigma
        FNUF_up: FNUFUp01sigma
        Material_down: MaterialDown01sigma
        Material_up: MaterialUp01sigma
    finalfit_sample_name_map: # pq: ff; Samples not in name map will keep their original names
        GGJets: GGJets
        DDQCDGJET: DDQCDGJets
        TTGG: TTGG
        TT: TT
        TTG_10_100: TTG_10_100
        TTG_100_200: TTG_100_200
        TTG_200: TTG_200
        ttHtoGG_M_125: ttHToGG
        BBHto2G_M_125: bbHToGG
        GluGluHToGG_M_125: GluGluHToGG
        VBFHToGG_M_125: VBFHToGG
        VHtoGG_M_125: VHToGG
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: GluGluToHH_kl-1p00_kt-1p00_c2-0p00
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: GluGluToHH_kl-0p00_kt-1p00_c2-0p00
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: GluGluToHH_kl-2p45_kt-1p00_c2-0p00
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: GluGluToHH_kl-5p00_kt-1p00_c2-0p00
    # === Columns to Save ===
    # - Columns from the parquet file you want to save to the merged parquet file, ready for FinalFit.
    # - If desired, apply mapping parquet_name -> finalfit_name here for each column.
    # - Note that all *weight* columns are added automatically, so no need to list them here.
    # - Also, all components of the score column are unpacked automatically, so no need to list them here. 
    #   - Their names are defined in score_idx_name_map below.
    # - If you need to rename specific weight columns, you can do so by manually specifying them in columns_to_save as `newname: oldname`.
    columns_to_save: # name map pq: ff; automatically adds all *weight* and unpacks *score* columns, so no need to list them here
        # old: new
        lumi: lumi
        event: event
        run: run
        mass: mass
        nonResReg_dijet_mass_DNNreg: dijet_mass
        year: year
        # is_boosted: is_boosted
        # y_proba: y_proba
        sample: sample
        score: score
    dijet_mass_key: nonResReg_dijet_mass_DNNreg # special variable; true name in events.parquet; renamed to dijet_mass for FF; must be a KEY in finalfit_var_name_map
    score_key: score # special variable for storing the multi-class scores
    score_idx_name_map: # mapping from score column index to class name for unpacking the score column
        0: nonRes_score
        1: ttH_score
        2: singleH_score
        3: HH_score