import json
import argparse

# 
# Need a way to get the different mHH trainings.
#  - mHH range for a single input
#  - list of mHH, assume set file structure?
# Need a way to get different mHH categories from a single training.
#  - Update mHH training to output like m

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input_file", type=str, dest="input_file", required=True, help="Path to input file generated by the categorization script.")
parser.add_argument("--n_cats", type=int, default=3)
parser.add_argument("--do_mjjcut", action="store_true", default=False)
args = parser.parse_args()

output_file = args.input_file[:-5] + "_finalfits.json"


dict_scoremap = {"th_signal": "ggHH_score",
                "th_bg_0": "nonRes_score",
                "th_bg_1": "ttH_score",
                "th_bg_2": "singleH_score"}

with open(args.input_file, 'r') as file:
    dict_cats_in = json.load(file)

dict_cats_ff = {}

catstr_nots = ""
icat = 0
while icat < args.n_cats:
    catstr = ""
    if args.do_mjjcut:
        catstr += "(dijet_mass > 80 & dijet_mass < 190) & "

    cuts = dict_cats_in[icat]

    catstr += f"(ggHH_score > {cuts['th_signal']} & nonRes_score < {cuts['th_bg_0']} & ttH_score < {cuts['th_bg_1']} & singleH_score < {cuts['th_bg_2']})"

    dict_cats_ff[f"cat{icat+1}"] = catstr + catstr_nots


    catstr_nots += " & not" + catstr
    icat += 1

with open(output_file, "w") as file:
    json.dump(dict_cats_ff, file, indent=4)